@urlBase=http://localhost:4000

### cadastro
POST {{urlBase}}/cadastrar
Content-Type: application/json

{
    "email":"ana3@mail.com",
    "senha":"a"
}

### login 
# @name postLogin
POST {{urlBase}}/login
Content-Type: application/json

{
    "email":"ana@mail.com",
    "senha":"a"
}

###
@token = {{postLogin.response.body.token}}

###
GET {{urlBase}}/info/atores
Authorization: Bearer {{token}}